// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/13/2026, 10:48:00 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/shomatakeda/Desktop/mahjong-tracker/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shomatakeda/Desktop/mahjong-tracker/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shomatakeda/Desktop/mahjong-tracker/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shomatakeda/Desktop/mahjong-tracker/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shomatakeda/Desktop/mahjong-tracker/plugins/**/*.{js,ts,mjs}","/Users/shomatakeda/Desktop/mahjong-tracker/composables/**/*.{js,ts,mjs}","/Users/shomatakeda/Desktop/mahjong-tracker/utils/**/*.{js,ts,mjs}","/Users/shomatakeda/Desktop/mahjong-tracker/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shomatakeda/Desktop/mahjong-tracker/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/shomatakeda/Desktop/mahjong-tracker/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/shomatakeda/Desktop/mahjong-tracker/app.config.{js,ts,mjs}","/Users/shomatakeda/Desktop/mahjong-tracker/app/spa-loading-template.html"]}},
{"theme":{"extend":{"colors":{"felt":{"50":"#1a2836","100":"#243445","200":"#2f4254","DEFAULT":"#0f1923"},"jade":{"DEFAULT":"#1a9b7a","light":"#2ed4a4"},"gold":"#d4a853"}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;